# Generated by Django 3.0.6 on 2020-06-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('photo', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField()),
                ('purchases', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
