# Generated by Django 3.0.6 on 2020-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200623_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_basket',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
