# Generated by Django 3.0.6 on 2020-06-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200620_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='archival',
            new_name='is_archival',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
