# Generated by Django 3.0.6 on 2020-06-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_in_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_basket',
        ),
    ]
