# Generated by Django 3.0.6 on 2020-06-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_in_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='shop/product/slav.png', upload_to='shop/product'),
        ),
    ]
