# Generated by Django 3.0.6 on 2020-06-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200620_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(height_field=450, upload_to='shop/product', width_field=800),
        ),
    ]
