# Generated by Django 3.0.6 on 2020-06-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200626_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
